
import { expect } from "chai";
import { ethers } from "hardhat";
import { buildPoseidon } from "circomlibjs";

describe("ZKSRP System Test", function () {
    let socialRecoveryVault: any;
    let guardianVerifier: any;
    let owner: any;
    let guardian: any;
    let newOwner: any;
    let poseidon: any;

    // Test Data
    const policyId = ethers.keccak256(ethers.toUtf8Bytes("test-policy-1"));
    const recoveryRequestId = ethers.keccak256(ethers.toUtf8Bytes("recovery-req-1"));
    const sharedSecret = 123456789n;

    // Helper to hash using Poseidon (mimicking the circuit)
    async function poseidonHash(inputs: any[]) {
        const hash = poseidon(inputs);
        // Convert field element to hex string (bytes32)
        const hashHex = BigInt(poseidon.F.toString(hash)).toString(16);
        return "0x" + hashHex.padStart(64, "0");
    }

    before(async function () {
        [owner, guardian, newOwner] = await ethers.getSigners();
        poseidon = await buildPoseidon();
    });

    it("1. Should deploy contracts successfully", async function () {
        // Deploy Verifier
        const Verifier = await ethers.getContractFactory("contracts/GuardianVerifier.sol:Groth16Verifier");
        guardianVerifier = await Verifier.deploy();
        await guardianVerifier.waitForDeployment();

        // Deploy Vault
        const Vault = await ethers.getContractFactory("contracts/SocialRecoveryVault.sol:SocialRecoveryVault");
        socialRecoveryVault = await Vault.deploy(await guardianVerifier.getAddress());
        await socialRecoveryVault.waitForDeployment();

        expect(await socialRecoveryVault.contractOwner()).to.equal(owner.address);
    });

    it("2. Should register a recovery policy", async function () {
        const tx = await socialRecoveryVault.registerPolicy(
            policyId,
            owner.address, // recoveryController
            owner.address, // aggregator
            1, // threshold
            1  // totalGuardians
        );
        await tx.wait();

        const policy = await socialRecoveryVault.policyInfo(policyId);
        expect(policy.owner).to.equal(owner.address);
        // policy.exists check removed as it is not returned by policyInfo
    });

    it("3. Should update Merkle Root (Commitment Batch)", async function () {
        // In a real scenario, we calculate this root from the tree of commitments.
        // Here we use a dummy root for demonstration.
        const dummyRoot = ethers.keccak256(ethers.toUtf8Bytes("dummy-root"));

        await socialRecoveryVault.registerCommitmentBatch(policyId, dummyRoot, 1);

        const policy = await socialRecoveryVault.policyInfo(policyId);
        expect(policy.merkleRoot).to.equal(dummyRoot);
    });

    it("4. Should initiate recovery process", async function () {
        await socialRecoveryVault.initiateRecovery(policyId, recoveryRequestId, newOwner.address);

        const state = await socialRecoveryVault.approvalsOf(policyId, recoveryRequestId);
        expect(state.isActive).to.be.true;
        expect(state.proposedOwner).to.equal(newOwner.address);
    });

    it("5. Should fail to submit invalid proof (Mock Check)", async function () {
        // Since we don't have a valid ZK proof generated by the circuit in this test environment yet
        // (requires .wasm and .zkey setup), we expect the contract to reject invalid proofs.

        const dummyProof = ethers.toUtf8Bytes("invalid-proof");
        const nullifier = await poseidonHash([sharedSecret, recoveryRequestId]);

        const publicInputs = {
            policyId: policyId,
            recoveryRequestId: recoveryRequestId,
            merkleRoot: await (await socialRecoveryVault.policyInfo(policyId)).merkleRoot,
            nullifier: nullifier,
            newOwner: newOwner.address
        };

        // This should revert because the Verifier contract will reject the dummy proof
        // OR the contract checks will fail.

        await expect(
            socialRecoveryVault.submitApproval(policyId, recoveryRequestId, dummyProof, publicInputs)
        ).to.be.reverted;
    });
});
